### PR TITLE
SOPS: Decrypt Kubernetes secrets generated by kustomize

### PR DESCRIPTION
**Pull request by bob-rohan**
Kustomize-controller can currently decrypt SOPS encrypted files - but
whole files only.

Kubernetes Secrets are base64 encoded, therefore when a SOPS encrypted
file, is added as base64 encoded data to a Kubernetes Secret, it is not
decrypted.

Fix: #328

### CODE REVIEW

**Review by stefanprodan — COMMENTED** [review]
@bob-rohan can you please add a sub-section here https://github.com/fluxcd/kustomize-controller/blob/main/docs/spec/v1beta1/kustomization.md#secrets-decryption and document the new decryption option. Please mention kustomize secret generator and how to use it.

**Comment by stefanprodan** [comment]
@bob-rohan can you please squash all commits into a single one and rename it to "Decrypt base64 encoded SOPS encrypted secrets". Thanks!

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @bob-rohan 🏅

**Comment by apeschel** [comment]
Thank you @bob-rohan, this is fantastic work!

**Pull request merged**
