### PR TITLE
sops: ensure proper wiring to default server

### PR DESCRIPTION
**Pull request by souleb**
make sure we use the right service to encrypt.

### CODE REVIEW

**Comment by stefanprodan** [comment]
> make sure we use the right service to encrypt

But we don't encrypt anything

**Comment by hiddeco** [comment]
That does not really matter, as the intent of the full implementation is that it should work anyway for e.g. potential further integration in the Flux CLI (or something).

This is technically a bug, and is right to be addressed :-).

**Review by hiddeco — APPROVED** [review]

**Comment by hiddeco** [comment]
@souleb the commit takes care of encryption but mentions "decryption".

**Comment by souleb** [comment]
@hiddeco sorry 🙏 , I have rewritten the commit message.

**Pull request merged**
