### PR TITLE
fix: prevent nil pointer dereference in health checks

### PR DESCRIPTION
**Pull request by makkes**
The `lastStatus` map now stores `event.ResourceStatus` values instead
of pointers to them, preventing nil pointers being dereferenced by
accident.

refs https://github.com/fluxcd/kustomize-controller/pull/374

Signed-off-by: Max Jonas Werner <mail@makk.es>

### CODE REVIEW

**Comment by makkes** [comment]
@stefanprodan as promised.

**Comment by hiddeco** [comment]
Wouldn't this result in L92-100 tripping because it now deals with an initialized but empty object, and wouldn't it thus be better to keep the pointer list, but deal with `nil` values there?

(In general I think, pointer object lists often use pointers because `nil` has a special meaning, and you want to maintain this information for as long as you may need it).

**Review by hiddeco — APPROVED** [review]
This addresses all my (personal) previous concerns, thank you @makkes :100:

**Comment by hiddeco** [comment]
DCO signoff (and while you are at it, a smash of) commits is still required.

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @makkes

**Pull request merged**
