### PR TITLE
feat: make it easier to reason about health check failures

### PR DESCRIPTION
**Pull request by makkes**
Whenever a health check times out now, the most recently collected error for each resource will be printed as part of the error message. This excludes errors for those resources for which no error was reported in the last update. This is because whenever a timeout occurs, an error is reported on ALL resources, even those that have been seen as healthy before.

Also, this commit causes all successfully checked resources to be omitted in the error event.

This is how it will look in the API:

Before:
```
$ k -n flux-system get events --field-selector=involvedObject.kind=Kustomization -w
LAST SEEN   TYPE     REASON   OBJECT                MESSAGE
34m         Normal   info     kustomization/test1   configmap/test1 created
32m         Normal   info     kustomization/test1   Update completed
0s          Normal   error    kustomization/test1   Health check timed out for [Deployment 'default/fails', Deployment 'default/fails2', Job 'default/wrong', Deployment 'default/git']

```

After:
```
$ k -n flux-system get events --field-selector=involvedObject.kind=Kustomization -w
LAST SEEN   TYPE     REASON   OBJECT                MESSAGE
34m         Normal   info     kustomization/test1   configmap/test1 created
32m         Normal   info     kustomization/test1   Update completed
0s          Normal   error    kustomization/test1   Health check failed for [Deployment 'default/fails' (status 'InProgress'): context deadline exceeded, Deployment 'default/fails2' (status 'NotFound'): context deadline exceeded, Job 'default/wrong' (status 'Unknown'): no matches for kind "Job" in group ""]
```

Signed-off-by: Max Jonas Werner <mail@makk.es>

### CODE REVIEW

**Comment by makkes** [comment]
Another spec I tested:
```
[...]
  healthChecks:
  - apiVersion: v1
    kind: Job
    name: somejob
    namespace: default
  - apiVersion: apps/v1
    kind: Deployment
    name: fails
    namespace: default
  - apiVersion: apps/v1
    kind: Deployment
    name: succeeds
    namespace: default
[...]

Events:
```
0s          Normal   error    kustomization/test1   Health check failed for [Deployment 'default/fails', Job 'default/somejob']: no matches for kind "Job" in group ""
0s          Normal   error    kustomization/test1   Health check failed for [Job 'default/somejob', Deployment 'default/fails', Deployment 'default/succeeds']: no matches for kind "Job" in group ""
```
Not exactly sure why sometimes the succeeding Deployment is part of that slice.

**Comment by stefanprodan** [comment]
So looks like we can capture only one error. Can you please try with 2 failed deployments and one ok.

**Comment by makkes** [comment]
Yep, I'm on it and also trying to find a neat way to catch all errors. But I need to dig into cli-utils a little more.

**Comment by hiddeco** [comment]
https://pkg.go.dev/k8s.io/apimachinery/pkg/util/errors may of help her to collect an aggregation of errors.

**Comment by makkes** [comment]
> So looks like we can capture only one error. Can you please try with 2 failed deployments and one ok.

@stefanprodan this is how it looks like with two failing Deployments and one succeeding:
```
0s          Normal   error    kustomization/k   Health check failed for [Deployment 'default/fails', Deployment 'default/dep', Deployment 'default/fails2']: Deployment 'default/dep': context deadline exceeded, Deployment 'default/fails2': context deadline exceeded, Deployment 'default/fails': context deadline exceeded
```
As you can see, it shows all 3 of them as timed out, even though the 'default/dep' one is always healthy. It looks like the timing out of one resources check leads to errors being reported for all of them.

**Comment by makkes** [comment]
Ok, this version works with 1 successful and 2 failing ones:
```
0s          Normal   error    kustomization/k   Health check failed for [Deployment 'default/fails2', Deployment 'default/fails', Deployment 'default/dep']: Deployment 'default/fails2': context deadline exceeded, Deployment 'default/fails': context deadline exceeded
```

**Comment by makkes** [comment]
@stefanprodan @hiddeco ready for another round of reviews, please. 🙂

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @makkes 🏅  I really like that we also show the status condition reason 👌

**Comment by makkes** [comment]
> @makkes Do you see a scenario where `lastStatus[rs.Identifier]` potentially could be nil?
> 
> ```
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1bc3985]
> 
> goroutine 309 [running]:
> github.com/fluxcd/kustomize-controller/controllers.(*KustomizeHealthCheck).Assess(0xc0009c3b78, 0x3b9aca00, 0x0, 0x0)
> 	/workspace/controllers/kustomization_healthcheck.go:90 +0x425
> github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).checkHealth(0xc00083e5a0, 0x2381328, 0xc0009af710, 0xc00000fd98, 0x1c15899, 0xd, 0xc0009a2ba0, 0x23, 0xc0000587d0, 0xd, ...)
> 	/workspace/controllers/kustomization_controller.go:744 +0xfd
> github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).reconcile(0xc00083e5a0, 0x2381328, 0xc0009af710, 0x1c15899, 0xd, 0xc0009a2ba0, 0x23, 0xc0000587d0, 0xd, 0x0, ...)
> 	/workspace/controllers/kustomization_controller.go:385 +0xf7b
> github.com/fluxcd/kustomize-controller/controllers.(*KustomizationReconciler).Reconcile(0xc00083e5a0, 0x2381328, 0xc0009af710, 0xc0000587f0, 0x8, 0xc0000587d0, 0xd, 0xc0009af700, 0x0, 0x0, ...)
> 	/workspace/controllers/kustomization_controller.go:233 +0xe58
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00089dea0, 0x2381280, 0xc000776000, 0x1e16e60, 0xc0002651a0)
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298 +0x30d
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00089dea0, 0x2381280, 0xc000776000, 0x0)
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253 +0x205
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0002eb480, 0xc00089dea0, 0x2381280, 0xc000776000)
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214 +0x6b
> created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:210 +0x425
> ```

Hu, I'll need to take a look to find a scenario where that might happen.

**Comment by stefanprodan** [comment]
@makkes why is the map made out of pointers? we should change it to values or check for nil before each operation .

**Comment by makkes** [comment]
@stefanprodan the main reason is that `collector.ResourceStatusCollector`'s `ResourceStatuses` is also a map of pointers:
```
type ResourceStatusCollector struct {
[...]
	ResourceStatuses map[object.ObjMetadata]*event.ResourceStatus
[...]
}
```
But I agree we should just skip nils. I'll put up a PR.

**Comment by stefanprodan** [comment]
thanks @makkes

**Pull request merged**
